### ISSUE TITLE
Error with Capistrano 3.6

### ISSUE THREAD

**Issue by bgkavinga** [railsware/capistrano-patch#1]
I am getting following error when try to use with capistrano v3.6
`cap aborted!
NoMethodError: undefined method `instance' for Capistrano::Configuration:Class
Did you mean?  instance_of?
/home/kavinga/.gem/ruby/2.4.0/gems/capistrano-patch-0.0.2/lib/capistrano/patch.rb:3:in `<top (required)>'
/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
/home/kavinga/tmp/cap-patch/Capfile:8:in `<top (required)>'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/rake_module.rb:28:in `load'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/rake_module.rb:28:in `load_rakefile'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:687:in `raw_load_rakefile'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:96:in `block in load_rakefile'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:95:in `load_rakefile'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:79:in `block in run'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/home/kavinga/.gem/ruby/2.4.0/gems/capistrano-3.6.1/lib/capistrano/application.rb:14:in `run'
/home/kavinga/.gem/ruby/2.4.0/gems/capistrano-3.6.1/bin/cap:3:in `<top (required)>'
/home/kavinga/.gem/ruby/2.3.0/bin/cap:22:in `load'
/home/kavinga/.gem/ruby/2.3.0/bin/cap:22:in `<main>'
LoadError: cannot load such file -- capistrano/patch
/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/kavinga/tmp/cap-patch/Capfile:8:in `<top (required)>'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/rake_module.rb:28:in `load'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/rake_module.rb:28:in `load_rakefile'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:687:in `raw_load_rakefile'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:96:in `block in load_rakefile'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:95:in `load_rakefile'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:79:in `block in run'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/usr/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/home/kavinga/.gem/ruby/2.4.0/gems/capistrano-3.6.1/lib/capistrano/application.rb:14:in `run'
/home/kavinga/.gem/ruby/2.4.0/gems/capistrano-3.6.1/bin/cap:3:in `<top (required)>'
/home/kavinga/.gem/ruby/2.3.0/bin/cap:22:in `load'
/home/kavinga/.gem/ruby/2.3.0/bin/cap:22:in `<main>'
`

**Comment by isaachbn** [comment]
Any ideas on how to solve this problem?

**Comment by ayanko** [comment]
Create issue about supporting recent versions. Looks like it is now toooo outdated.

**Comment by isaachbn** [comment]
This bug apply in version latest @ayanko .

![Screenshot from 2020-02-10 14-23-24](https://user-images.githubusercontent.com/3923258/74173533-03cad180-4c11-11ea-8890-c1277ef94f21.png)
